---
name: "TriliumNext Notes"
version: "v0.96.0"
slug: trilium_next
description: "Hierarchical note-taking application with encryption, Markdown support, and personal knowledge base features"
url: "https://github.com/triliumnext/trilium"
ingress: true
ingress_port: 8080
ingress_stream: true
panel_icon: mdi:notebook-multiple
panel_title: Trilium
webui: "http://[HOST]:[PORT:8080]/"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
map:
  - type: data
    read_only: false
    path: /data/trilium-data
  - type: config
    read_only: false
    path: /config
ports:
  "8080/tcp": 8080
options:
  timezone: "Europe/Berlin"
  log_level: "info"
  https_only: false
schema:
  timezone: |
    list(Europe/Berlin|America/New_York|UTC|Asia/Berlin|Europe/London|Asia/Tokyo|Australia/Sydney)
  log_level: "list(trace|debug|info|notice|warning|error|fatal)"
  https_only: "bool"
environment:
  # Minimal environment variables
  TRILIUM_DATA_DIR: "/data/trilium-data"
  TZ: "{{ options.timezone }}"
  NODE_ENV: "production"
  HOST: "0.0.0.0"
  # Let Trilium use its default configuration
  TRILIUM_CONFIG_INI_PATH: "/data/trilium-data/trilium-config.json"
