{
  "name": "Trilium Next - JB",
  "version": "v2025.03.12",
  "slug": "triliumnext",
  "description": "TriliumNext Notes is a hierarchical note taking application with focus on building large personal knowledge bases. It also supports encryption, Markdown, and other PKB features.",
  "url": "https://github.com/triliumnext/trilium",

  "ingress": true,
  "ingress_stream": true,
  "ingress_port": 8080,
  "webui": "http://[HOST]:[PORT:8080]/",
  "panel_icon": "mdi:notebook-multiple",
  "panel_title": "Trilium Notes",

  "arch": [
    "amd64",
    "aarch64",
    "armhf",
    "armv7",
    "i386"
  ],

  "startup": "application",
  "boot": "auto",
  "init": false,

  "map": [
    "addon_config:rw",
    {
      "type": "data",
      "read_only": false,
      "path": "/home/node/trilium-data"
    }
  ],

  "expose": {
    "8080/tcp": {}
  },
  "ports_description": {
    "8080/tcp": "Web interface"
  },

  "options": {
    "NO_AUTHENTICATION": true,
    "TRILIUM_OAUTH_BASE_URL": "",
    "TRILIUM_OAUTH_CLIENT_ID": "",
    "TRILIUM_OAUTH_CLIENT_SECRET": "",
    "TRILIUM_OAUTH_ISSUER_BASE_URL": "",
    "TRILIUM_OAUTH_ISSUER_NAME": "",
    "timezone": "Europe/Berlin",
    "log_level": "info",
    "https_only": false
  },

  "schema": {
    "NO_AUTHENTICATION": { "type": "boolean" },
    "TRILIUM_OAUTH_BASE_URL": { "type": "string" },
    "TRILIUM_OAUTH_CLIENT_ID": { "type": "string" },
    "TRILIUM_OAUTH_CLIENT_SECRET": { "type": "string" },
    "TRILIUM_OAUTH_ISSUER_BASE_URL": { "type": "string" },
    "TRILIUM_OAUTH_ISSUER_NAME": { "type": "string" },
    "timezone": {
      "type": "select",
      "options": [
        "Europe/Berlin",
        "America/New_York",
        "UTC",
        "Asia/Berlin",
        "Europe/London",
        "Asia/Tokyo",
        "Australia/Sydney"
      ]
    },
    "log_level": {
      "type": "select",
      "options": [
        "trace","debug","info","notice","warning","error","fatal"
      ]
    },
    "https_only": { "type": "boolean" }
  },

  "environment": {
    "TRILIUM_DATA_DIR": "/home/node/trilium-data",
    "NO_AUTHENTICATION": "{{ options.NO_AUTHENTICATION }}",
    "TZ": "{{ options.timezone }}",
    "NODE_ENV": "production",
    "HOST": "0.0.0.0",
    "TRILIUM_LOG_LEVEL": "{{ options.log_level }}"
  },

  "image": "triliumnext/notes:v2025.03.12",
  "upstream": "v2025.03.12"
}
