{
  "arch": [
    "amd64",
    "aarch64", 
    "armhf",
    "armv7",
    "i386"
  ],
  "boot": "auto",
  "description": "TriliumNext Notes is a hierarchical note taking application with focus on building large personal knowledge bases.",
  "environment": {
    "TRILIUM_DATA_DIR": "/data/trilium-data",
    "USER_UID": "1000",
    "USER_GID": "1000", 
    "TMPDIR": "/data/tmp",
    "TEMP": "/data/tmp",
    "NO_AUTHENTICATION": "true",
    "TRILIUM_OAUTH_BASE_URL": "",
    "TRILIUM_OAUTH_CLIENT_ID": "",
    "TRILIUM_OAUTH_CLIENT_SECRET": "",
    "TRILIUM_OAUTH_ISSUER_BASE_URL": "",
    "TRILIUM_OAUTH_ISSUER_NAME": ""
  },
  "name": "Trilium Next - Test",
  "map": [
    {
      "type": "data",
      "read_only": false,
      "path": "/data"
    }
  ],
  "options": {},
  "expose": {
    "8080/tcp": {}
  },
  "ports_description": {
    "8080/tcp": "Web interface"
  },
  "schema": {
    "TRILIUM_OAUTH_BASE_URL": "str?",
    "TRILIUM_OAUTH_CLIENT_ID": "str?",
    "TRILIUM_OAUTH_CLIENT_SECRET": "str?",
    "TRILIUM_OAUTH_ISSUER_BASE_URL": "str?",
    "TRILIUM_OAUTH_ISSUER_NAME": "str?"
  },
  "slug": "triliumnex
