name: TrilliumNext Update Dockerfile, Entrypoint, and package.json

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List repo root before downloads
        run: ls -la

      - name: Download rootless Dockerfile
        run: curl -o Dockerfile https://raw.githubusercontent.com/TriliumNext/Notes/develop/apps/server/Dockerfile.alpine.rootless

      - name: Download rootless entrypoint script
        run: curl -o rootless-entrypoint.sh https://raw.githubusercontent.com/TriliumNext/Notes/develop/apps/server/rootless-entrypoint.sh

      - name: Download latest package.json from upstream
        run: curl -o trillium/package.json.new https://raw.githubusercontent.com/TriliumNext/Trilium/main/package.json

      - name: List repo root after downloads
        run: ls -la

      - name: Patch Dockerfile for Home Assistant add-on
        run: |
          # Change data dir
          sed -i 's|/home/trilium-data|/data|g' Dockerfile

          # Add TRILIUM_DATA_DIR if missing
          grep -q 'ENV TRILIUM_DATA_DIR' Dockerfile || echo 'ENV TRILIUM_DATA_DIR=/data' >> Dockerfile

          # Remove problematic COPY for ./dist
          sed -i '/COPY\s\+\.\/*dist/d' Dockerfile

          # Fix COPY for package.json to point to correct path
          sed -i 's|COPY\s\+\./docker/package.json.*|COPY ./package.json /usr/src/app/|' Dockerfile

      - name: List repo root after patching Dockerfile
        run: ls -la

      - name: Check for changes and move files
        id: move_and_check
        run: |
          mv Dockerfile trillium/Dockerfile.new
          mv rootless-entrypoint.sh trillium/rootless-entrypoint.sh.new

          CHANGED=0

          for file in Dockerfile rootless-entrypoint.sh package.json; do
            new_file="trillium/$file.new"
            old_file="trillium/$file"
            if [ ! -f "$old_file" ] || ! cmp -s "$new_file" "$old_file"; then
              mv "$new_file" "$old_file"
              echo "$file changed or added."
              CHANGED=1
            else
              rm "$new_file"
            fi
          done

          echo "changed=$CHANGED" >> $GITHUB_OUTPUT

      - name: List trillium folder after moving files
        run: ls -la trillium

      - name: Commit and push if changed
