name: Update README with Version

on:
  workflow_dispatch:
  push:
    paths:
      - 'trillium/build.yaml'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files for debugging
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of 'trillium' directory:"
          ls -al trillium/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Parse version from build.yaml
        id: parse_version
        run: |
          VERSION=$(grep 'amd64:' trillium/build.yaml | awk -F ':' '{print $3}' | xargs)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version extracted: $VERSION"

      - name: Update trillium/README.md with version
        if: env.VERSION
        run: |
          sed -i -E "s#TriliumNext Notes for Home Assistant Version: v[0-9]+\.[0-9]+\.[0-9]+#TriliumNext Notes Version: ${VERSION} for Home Assistant#g" trillium/README.md
          echo "trillium/README.md updated with version ${VERSION}."

      - name: Commit changes
        if: env.VERSION
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if ! git diff --quiet trillium/README.md; then
            echo "Changes detected in trillium/README.md. Committing..."
            git add trillium/README.md
            git commit -m "Docs: Update README in trillium/ with version ${VERSION}"
            git push
          else
            echo "No changes to commit."
          fi
