name: V2 TrilliumNext Update Upstream Version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # every day at 6:00 UTC

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get latest release metadata from triliumnext/notes
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const res = await github.rest.repos.getLatestRelease({
              owner: 'triliumnext',
              repo: 'notes'
            });
            core.setOutput("tag", res.data.tag_name);
            core.setOutput("body", res.data.body);

      - name: Save changelog to file
        run: echo "${{ steps.get_release.outputs.body }}" > changelog.txt

      - name: Check & update version files
        env:
          LATEST_VERSION: ${{ steps.get_release.outputs.tag }}
        run: |
          ADDON_DIR="./trilliumnext"
          CURRENT_VERSION=$(jq -r '.upstream_version' "$ADDON_DIR/updater.json")

          echo "Current: $CURRENT_VERSION | Latest: $LATEST_VERSION"

          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Updating files to version $LATEST_VERSION"

            TODAY=$(date +'%d-%m-%Y')

            # Update updater.json
            jq --arg v "$LATEST_VERSION" --arg d "$TODAY" \
              '.upstream_version = $v | .last_update = $d' "$ADDON_DIR/updater.json" > tmp && mv tmp "$ADDON_DIR/updater.json"

            # Update config.json
            jq --arg v "$LATEST_VERSION" \
              '.version = $v | .upstream = $v' "$ADDON_DIR/config.json" > tmp && mv tmp "$ADDON_DIR/config.json"

            # Save changelog with versioned filename
            cp changelog.txt "$ADDON_DIR/CHANGELOG_$LATEST_VERSION.md"

            # Commit and push changes
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add "$ADDON_DIR/updater.json" "$ADDON_DIR/config.json" "$ADDON_DIR/CHANGELOG_$LATEST_VERSION.md"
            git commit -F changelog.txt -m "Update to upstream version $LATEST_VERSION"
            git push
          else
            echo "No update needed"
          fi
