name: TrilliumNext Update Upstream Version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # every day at 6:00 UTC

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get latest release from triliumnext/notes
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const res = await github.rest.repos.getLatestRelease({
              owner: 'triliumnext',
              repo: 'notes'
            });
            return {
              tag_name: res.data.tag_name,
              body: res.data.body
            };

      - name: Check & update version files
        env:
          LATEST_VERSION: ${{ fromJson(steps.get_release.outputs.result).tag_name }}
          CHANGELOG: ${{ fromJson(steps.get_release.outputs.result).body }}
        run: |
          ADDON_DIR="./trilliumnext"
          CURRENT_VERSION=$(jq -r '.upstream_version' "$ADDON_DIR/updater.json")

          echo "Current: $CURRENT_VERSION | Latest: $LATEST_VERSION"

          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Updating files to version $LATEST_VERSION"

            TODAY=$(date +'%d-%m-%Y')

            # Update updater.json
            jq --arg v "$LATEST_VERSION" --arg d "$TODAY" \
              '.upstream_version = $v | .last_update = $d' "$ADDON_DIR/updater.json" > tmp && mv tmp "$ADDON_DIR/updater.json"

            # Update config.json
            jq --arg v "$LATEST_VERSION" \
              '.version = $v | .upstream = $v' "$ADDON_DIR/config.json" > tmp && mv tmp "$ADDON_DIR/config.json"

            # Optionally save changelog to a file
            echo "$CHANGELOG" > "$ADDON_DIR/CHANGELOG_$LATEST_VERSION.md"

            # Commit and push
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add "$ADDON_DIR/updater.json" "$ADDON_DIR/config.json" "$ADDON_DIR/CHANGELOG_$LATEST_VERSION.md"
            git commit -m "Update to upstream version $LATEST_VERSION

$CHANGELOG"
            git push
          else
            echo "No update needed"
