name: Build and Push TriliumNext Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Clone upstream TriliumNext repo
        run: |
          git clone --depth=1 https://github.com/TriliumNext/Notes.git upstream

      - name: Copy server files to build context
        run: |
          cp -r upstream/apps/server ./server

      - name: Install dependencies and build Trilium frontend
        working-directory: ./server
        run: |
          apk add --no-cache nodejs npm  # or use Node.js setup action
          npm install -g pnpm
          pnpm install
          pnpm run build

      - name: Copy start script
        run: cp upstream/apps/server/start-docker.sh ./server/start-docker.sh && chmod +x ./server/start-docker.sh

      - name: Prepare Dockerfile
        run: |
          cp upstream/apps/server/Dockerfile.alpine ./Dockerfile
          sed -i 's|^WORKDIR .*|WORKDIR /data|' Dockerfile

      - name: Build Docker image
        run: |
          docker build -t jeakob/triliumnext:latest -f Dockerfile ./server

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: |
          docker push jeakob/triliumnext:latest
