name: Build and Push Trilium Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Clone upstream Trilium repo
        run: |
          git clone --depth 1 https://github.com/TriliumNext/Notes.git

      - name: Install dependencies and build
        working-directory: Notes/apps/server
        run: |
          pnpm install
          pnpm build

      - name: Fetch upstream Dockerfile
        run: |
          curl -o Dockerfile https://raw.githubusercontent.com/TriliumNext/Notes/develop/apps/server/Dockerfile.alpine

      - name: Update WORKDIR to /data in Dockerfile
        run: |
          sed -i 's|^WORKDIR .*|WORKDIR /data|' Dockerfile

      - name: Copy built files into build context
        run: |
          cp -r Notes/apps/server/dist ./dist
          cp -r Notes/apps/server/package.json ./package.json
          cp -r Notes/apps/server/pnpm-workspace.yaml ./pnpm-workspace.yaml
          cp -r Notes/apps/server/start-docker.sh ./start-docker.sh
          # copy any other required files from upstream server dir

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t jeakob/trilium-custom:latest .

      - name: Push Docker image
        run: |
          docker push jeakob/trilium-custom:latest
