name: Update Dockerfile, Build and Push Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Clone upstream TriliumNext repo
        run: |
          git clone --depth=1 https://github.com/TriliumNext/Notes.git

      - name: Update WORKDIR to /data in Dockerfile
        run: |
          sed -i 's|^WORKDIR .*|WORKDIR /data|' Notes/apps/server/Dockerfile.alpine

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies and build
        working-directory: Notes/apps/server
        run: |
          pnpm install
          pnpm run build

      - name: Build Docker image
        working-directory: Notes/apps/server
        run: docker build -t jeakob/triliumnext:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push jeakob/triliumnext:latest
