name: Update README with Version

on:
  push:
    paths:
      - build.yml  # Trigger workflow only when build.yml is modified

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Parse version from build.yml
      id: parse_version
      run: |
        import yaml
        
        # Read the build.yml file
        with open('build.yml', 'r') as file:
            config = yaml.safe_load(file)
        
        # Extract version info (we will use the amd64 version here)
        version = config['build_from']['amd64'].split(':')[1]  # Extract version after the colon
        
        # Save the version to an environment variable
        print(f"VERSION={version}")
        print(f"::set-output name=version::{version}")

    - name: Update README.md with version
      run: |
        VERSION="${{ steps.parse_version.outputs.version }}"
        
        # Replace the VERSION_PLACEHOLDER in the header
        sed -i "s/# TriliumNext Notes for Home Assistant Version: VERSION_PLACEHOLDER/# TriliumNext Notes for Home Assistant Version: ${VERSION}/g" README.md

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        
        # Commit and push changes to README.md
        git add README.md
        git commit -m "Update README with version ${VERSION}"
        git push
