name: Update Dockerfile and Build Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-dockerfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Clone TriliumNext upstream repo
        run: |
          git clone --depth=1 https://github.com/TriliumNext/Notes.git upstream

      - name: Copy required files for build context
        run: |
          cp upstream/apps/server/Dockerfile.alpine ./Dockerfile
          cp upstream/apps/server/start-docker.sh ./start-docker.sh
          chmod +x ./start-docker.sh
          # Copy the entire docker folder that includes pnpm-workspace.yaml
          cp -r upstream/apps/server/docker ./docker

      - name: Update WORKDIR in Dockerfile to /data
        run: |
          sed -i 's|^WORKDIR .*|WORKDIR /data|' Dockerfile

      - name: Build Docker image
        run: |
          docker build -t jeakob/triliumnext:latest .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: |
          docker push jeakob/triliumnext:latest
