name: Update Dockerfile and Build Image

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  update-dockerfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch upstream Dockerfile
        run: |
          curl -o Dockerfile https://raw.githubusercontent.com/TriliumNext/Notes/develop/apps/server/Dockerfile.alpine

      - name: Update WORKDIR to /data
        run: |
          sed -i 's|^WORKDIR .*|WORKDIR /data|' Dockerfile

      - name: Fetch upstream start-docker.sh
        run: |
          curl -o start-docker.sh https://raw.githubusercontent.com/TriliumNext/Notes/develop/apps/server/start-docker.sh
          chmod +x start-docker.sh

      - name: Build Docker image
        run: |
          docker build -t jeakob/triliumnext:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push jeakob/triliumnext:latest
