name: Update TriliumNext Addon Version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # every day at 6am UTC

jobs:
  update-triliumnext-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Clone TriliumNext
        run: |
          mkdir -p homeassistant-addons/triliumnext
          git clone --depth=1 https://github.com/TriliumNext/Notes ./homeassistant-addons/triliumnext

      - name: Get latest release version
        id: get_version
        run: |
          latest=$(curl -s https://api.github.com/repos/TriliumNext/Notes/releases/latest | jq -r .tag_name)
          echo "{\"version\": \"$latest\"}" > ./homeassistant-addons/triliumnext/updater.json
          echo "version=$latest" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add homeassistant-addons/triliumnext/updater.json
          git diff --cached --quiet || git commit -m "Update TriliumNext version to ${{ steps.get_version.outputs.version }}"
          git push
